### ISSUE TITLE
Cars no longer on roads

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#155]
Version: 2.11.0

In previous version I remember cars were on roads. In 2.11.0 I never saw cars anymore.

**Comment by uafr** [comment]
There are cars in front of the market and at the fire station but none on the road. It would look nice but we  never had cars on the road.

**Comment by FabioPedretti** [comment]
They were added in https://github.com/lincity-ng/lincity-ng/commit/c727641d13632cdd945a1ae03a794fb79ad4e4b1.

**Comment by uafr** [comment]
oops. Sorry, I never noticed any cars. Either I need new glasses or there are some issues that prevents them from working.

**Comment by dbear496** [comment]
This was introduced in 92f1cdcf555988cf61d7d86cd8c112d6187450b1 because waste fires on roads were changed so that the fire always exists in frameptr but it is only enabled when there is actually a fire. Cars are seeing this extra frame and not spawning because it interprets that another car is already on that road.

**Comment by dbear496** [comment]
This _can_ be fixed by increasing the threshold on [this line](https://github.com/lincity-ng/lincity-ng/blob/f42e76c379f46a3ee498a5e2b997c22db7dd70e4/src/lincity/lintypes.cpp#L985), but I think that is an ugly solution that is prone to more breakage in the future.
