### ISSUE TITLE
Farm output value reset on Save

### ISSUE THREAD

**Issue by Weolvi** [lincity-ng/lincity-ng#177]
After a longer pause with this game, I compiled and installed a fresh version from Github on August 23. Overall, the game is nice and stable, but I found an issue with the Farm Output value when continuing a saved game.

While the Tech value of the Farm is displayed correctly, the Output value will be falsely set to the current Tech value of the game. This can be seen easily because after loading a game, all Farms have the same Output value. At the moment can't say if this is a purely cosmetic error or if gameplay is affected.

**Comment by dbear496** [comment]
Indeed, during loading, the farm tech bonus was computed using the current tech level instead of the original tech level. I have submitted a patch for this issue.

**Comment by Weolvi** [comment]
First of all, thank for picking this up so fast!

Of course, I did not let the issue getting in the way of playing. :-) It turns out that a number of areas show the same behavior (getting updated to current tech level on load), such as windmills and coal power plants. So maybe there is an underlying issue in one of the base classes. Recycle Centers do not seem to be affected.

On a related note, but not a bug: Why do light and heavy industries have an associated tech level when it does not have an influence on the performance?

**Comment by dbear496** [comment]
It is not an issue with the base class, but it could be considered an issue with the load/save system which requires careful implementation for each module individually and is bug-prone. I will look into this issue for other constructions and fix those. In the longer term, I want to change the load-save system so that it is not so bug-prone.

Tech level for light and heavy industries affects how much they pollute. This feature is undocumented, so I will give you a rundown here.
- For tech below 100, they produce the standard amount of pollution (i.e. 100% pollution).
- For tech from 100 to 200, they pollute less and instead create waste (i.e. at tech 125, they produce 75% pollution and 25% waste).
- For tech from 200 to 300, they create no pollution and produce decreasing amounts of waste (i.e. at tech 225, they produce 75% waste).
- For tech above 300, no pollution or waste is produced.
Notably, this behavior does not apply to coal power stations.
