### ISSUE TITLE
More background music

### ISSUE THREAD

**Issue by blue-four-seven** [lincity-ng/lincity-ng#184]
Would it be okay to add more background music to the game?

**Comment by heikkiket** [comment]
Hello!
About 15 years ago I drafted a score for Lincity. I have been few times asking if someone thinks background music is needed but no positive answers. So I haven't invested creating a demo-version of the score. It would involve quite a bit of work.

**Comment by dbear496** [comment]
@heikkiket and @blue-four-seven If either of you want to produce music for the game, then I think that's great -- have at it. But if you don't want to, that's fine to. For me personally, background music is a low priority because I usually disable all sounds when playing the game, and if I want music, then I fire up Spotify. But I recognize that other people do care about the game music and sound effects.
