### ISSUE TITLE
lag and high CPU usage in some menu

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#201]
I noticed that in the Credits screen, there is noticeable lag scrolling the screen, and CPU usage is at 50% (according to top). To me this looks too much for a static screen. To check if there are specific issues. Eventually there should be a fps limiter in menu.

Options menu is also quite high at 13%.
New game menu is at 10%.
Introductory main menu is at around just 4%.

For reference, during the game (for example on Rocket_98) it is about 65% (max zoom in) to 110% (max zoom out).

**Comment by dbear496** [comment]
Thanks for bringing this up. Indeed I also see ~50% CPU when scrolling the credits screen. I'll look into it, but I have a feeling it will not be an easy fix.

**Comment by dbear496** [comment]
Actually, it probably is a simple fix...maybe we shouldn't **constantly** resize the window. I've narrowed the issue down to [this line](https://github.com/lincity-ng/lincity-ng/blob/0b1c54f972c5f3f4f7a97904492d652f14dac4bf/src/lincity-ng/MainMenu.cpp#L1067):
```
/* We unconditionally redraw every ~100 ms as workaround for an SDL bug
 * under Wayland, in which window resizing is not communicated to the
 * program until it redraws the window. When this bug is no longer
 * present, this behavior should be safe to remove */
if (ticks - lastRedrawTicks > 90) {
  currentMenu->reLayout();
}
```
Unfortunately, I can't find what Wayland/SDL issue the comment is referencing to know whether the issue is fixed upstream and hence whether I can remove these lines.

So far, I've only found issues related to toggling fullscreen, which is not what the comment infers:
- https://github.com/libsdl-org/SDL/issues/4562
- https://github.com/libsdl-org/SDL/issues/4572
- https://github.com/libsdl-org/SDL/issues/6219

I also found [this Arch forum post](https://bbs.archlinux.org/viewtopic.php?id=280039) that mentions the issue, but it doesn't provide a link the the actual issue.

Do I just remove the lines and hope all will be well? It [works for me](https://ubuntuforums.org/showthread.php?t=1293324) anyway.

**Comment by dbear496** [comment]
Good find. I ran a git blame, but I didn't know that commit was a squash.

**Comment by dbear496** [comment]
The in-game cpu utilization is a separate issue. Can you open a separate issue for that?

**Comment by dbear496** [comment]
I think I'll take the liberty to remove those three lines of code since the contributors who wrote those lines are not responding to confirm or deny whether those lines are still necessary.

**Comment by mstoeckl** [comment]
> @mstoeckl, @vorot93, do you have any updated suggestion about this issue?

If I recall correctly, the original symptoms where that, when resizing the window, the program would sometimes alternately submit frames in two different sizes. There have been a lot of changes to the SDL Wayland backend since then, and I can no longer reproduce the issue with the three lines removed.

**Comment by dbear496** [comment]
Thanks @mstoeckl for the background context to those lines.
