### ISSUE TITLE
physfsrwops build issues

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#203]
With #194 there is a build issue with the Debian package.

Full build log: https://launchpadlibrarian.net/755638531/buildlog_ubuntu-oracular-amd64.lincity-ng_2.11.2+git2410240400.0e0e49~oibaf~o_BUILDING.txt.gz

Error:

```
CMake Warning at /usr/share/cmake-3.30/Modules/FetchContent.cmake:2111 (message):
  FETCHCONTENT_FULLY_DISCONNECTED is set to true, which requires the source
  directory for dependency physfsrwops.c to already be populated.  This
  generally means it must not be set to true the first time CMake is run in a
  build directory.  The following source directory should already be
  populated, but it doesn't exist:

    /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/_deps/physfsrwops.c-src

  Policy CMP0170 controls enforcement of this requirement.
Call Stack (most recent call first):
  /usr/share/cmake-3.30/Modules/FetchContent.cmake:2384 (__FetchContent_Populate)
  src/PhysfsStream/CMakeLists.txt:31 (FetchContent_MakeAvailable)
```

Note that physfsrwops is currently not included in [libphysfs](https://packages.debian.org/source/sid/libphysfs) Debian package.

Also note that when building Debian packages, it is not permitted to download files from the net.

Possible alternatives:
- include these 2 files inside lincity-ng;
- add the 2 files to Debian libphysfs package (they are currently in the extras directory of [physfs](https://github.com/icculus/physfs), and thus not installed);
- modify Debian lincity-ng package to include the 2 files (note that it will likely happen with other distro packaging).

Also, I found these physfsrwops modifications, not sure if they may be useful (they are missing upstream):
- t-engine4: [leak](https://forums.te4.org/viewtopic.php?t=39396) / [other stuff](https://git.net-core.org/cinornu/t-engine4/-/commits/ubervo3-mobileport/src/physfs/physfsrwops.c?ref_type=heads)
- hedgewars: [physfsrwops.c](https://hg.hedgewars.org/hedgewars-draft/log/tip/misc/libphyslayer/physfsrwops.c) / [physfsrwops.h](https://hg.hedgewars.org/hedgewars-draft/log/tip/misc/libphyslayer/physfsrwops.h)

**Comment by dbear496** [comment]
The documentation for PHYSFS_close states:
```
return nonzero on success, zero on error.
```
So perhaps those issues you linked are from a different physfs version.

I do not prefer supplying the physfsrwops files internally because these files are really not part of lincity-ng -- they are part of physfs. Does the Debian repository just not host projects that use FetchContent? How is this usually done?

I do not believe fetching from the physfs GitHub repo is a security concern because the fetched files are verified by the checksums [here](https://github.com/lincity-ng/lincity-ng/blob/0e0e49e3798ee1383c198aedf9da529a6e687541/src/PhysfsStream/CMakeLists.txt#L23).

Another alternative would probably be to use git submodules, but I hesitate to even bring this up because git submodules are a major headache so I much prefer using CMake FetchContent.

This is not to say that I am unwilling to include these files in lincity-ng, but I would like to understand the dilemma better first.

**Comment by dbear496** [comment]
So it looks like packages that use FetchContent need to be configured prior to packaging or need their dependencies downloaded and included in the package. And neither of these options are really better, so including the files within the lincity-ng repo looks like the best solution.

I just need to figure out where to put the files. I want to get rid of the PhysfsStream directory because I do not think it is well utilized by the rest of the project.

**Comment by dbear496** [comment]
In fact, long-term goal: get rid of PhysFS altogether. PhysFS has some issues integrating with zlib because it is non-trivial to get the full platform-dependent filepath. C++ offers a cross-platform filesystem API with `std::filesystem` that can be used instead. PhysFS also provides features to find the base directory and write directory for the program in a cross-platform way. For this, we can just use some simple `#ifdef` macros or a much more light-weight dependency such as https://github.com/Malvineous/cfgpath.

**Comment by dbear496** [comment]
@FabioPedretti See if #214 fixes the issue.
