### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by lightdot** [lincity-ng/lincity-ng#27]
I'd like to package the game for a distro and it would be really helpful if there was a more recent release to grab.

Perhaps a 2.9 is in order..? It has been in a beta for a while! ;)

**Comment by heikkiket** [comment]
Hello!

That would be wonderful! At least I would enjoy playing a new version of
Lincity already.

I have a half-drafted new soundtrack for a game. I would compose and
produce it, if there would be a reasonable deadline. (I suggested this idea
few yerars back, but nobody seemed interested then so I didn't proceed:
this would be at least few months' work)

Heikki Ketoharju

--
http://heikki.ketoharju.info

**Comment by uafr** [comment]
Well unfortunately nobody had time to fix the issues found in beta. I guess most momentum was lost with switching hosts. I'm not even sure what problems were encountered, font issues, way to build on windows 10, replacement for Autopackage and probably more. 
Sorry, I have way too little spare time ATM.

**Comment by rzr** [comment]
hi,
If this project is abandoned, it can be transfered to:
https://abandonware.github.io/

As suggested on:
https://linuxfr.org/users/tarnyko/journaux/abandonware-un-orphelinat-pour-projets-oss-abandonnes

**Comment by uafr** [comment]
I don't see any advantage in doing yet another move after source to some other provider.

**Comment by Jamim** [comment]
Hello everyone,

[`2.9-beta`](https://github.com/lincity-ng/lincity-ng/releases/tag/lincity-ng-2.9-beta) is currently approaching 10th anniversary 🎂 🥳 

Are there any major issues preventing the new version from being released?
As I can see, there were no fresh commits for almost a year now and this projects definitely looks abandoned.

It would be great to have a bit more transparency on this topic.

Thanks!

**Comment by dbear496** [comment]
I think the repo owners just don't have a lot of time to look at it. I wish someone would hurry up and merge my slew of pull requests. I eventually stopped making new pull requests to avoid a mess of PR's depending on other PR's.

**Comment by heikkiket** [comment]
What about the fork mentioned in #76?

I do really think the best way going forward with this project would be a fork. Also, Git and GitHub are de-centralized systems, so nothing prevents from diverging and then merging again later.

kind regards
Heikki Ketoharju

**Comment by uafr** [comment]
On 2023-11-13 Aliaksei Urbanski ***@***.***> wrote:
> Are there any major issues preventing the new version from being
> released? As I can see, there were no fresh commits for almost a
> year now and this projects definitely looks abandoned.

No idea about the other devs, for me the main issue is my lack of
free time. But maybe I should just grab all the stuff from git,
see it if compiles and call it a release.

Wolfgang

**Comment by Jamim** [comment]
Hello @uafr,

> But maybe I should just grab all the stuff from git,
see it if compiles and call it a release.

It might be the way, but I believe it would be even better if you give a chance to #76 before that. Also, taking into account the lack of free time, you may consider granting some permissions on this repository to @Arcnor who seems capable and passionate enough to support this good old project.

In any case, thank you!

**Comment by dbear496** [comment]
If it would help at all, I could submit the master branch of my fork as a PR even though it depends on other PRs. This would wrap together all 6 of my existing PRs, the CMake transition from #76, and numerous other enhancements.

**Comment by dbear496** [comment]
I submitted #78, which includes most of the changes I have on my fork.

**Comment by dbear496** [comment]
@uafr and @v1993, I think it is about time that a repo owner merge my PRs. I have addressed every concern that has been raised in the discussion on my PR's so far, and they are almost a year old now. I have now accumulated 10 open PR's with still no signs of merging the first one. At this point, [my fork](https://github.com/dbear496/lincity-ng) is so far ahead just by merging these PR's, it would make sense to just merge the master branch of my fork into the mainline and bump the version number.

The most important PR is the upgrade from jam to cmake. Since I am now using a different build tool than the mainline master, it is almost impossible for me to base future PR's on the master branch. I have actually tried building the master branch recently, and jam throws a bunch of errors that I don't want to sort through because it's an old system anyway.

If no repo owners have time to even merge a PR, then I propose that I be granted permissions to the master branch so that I can merge them myself.

**Comment by Arcnor** [comment]
Hey @dbear496 , how's it going?

I really have no skin on this game, as I just made that CMake PR to help a bit with the project, but my 2c are: I think at this point is clear that the original maintainers are either burnt off or just busy with life in general, this is completely ok, life gets in the way and all that.

My opinion is that you should just keep your fork alive, as you still seem passionate about the game and don't bother with opening PRs here, as it's a waste of time IMHO. You can open a ticket here pointing people to your fork and that will be enough.

Good luck!

**Comment by dbear496** [comment]
Yeah, you're probably right. It's no use trying to get things merged.

**Comment by asl97** [comment]
> If no repo owners have time to even merge a PR, then I propose that I be granted permissions to the master branch so that I can merge them myself.

That would be kind of irresponsible if the repo owners do that, repos get hijacked with malware getting added that way.

and who knows if downstream is automatically pulling from this repo.

I believe the best way forward is a fork (bonus if there's a name change), this itself was a unofficial fork of the svn on sourceforge as far as I am aware of, even the original website and a few wiki on the web doesn't have mention of this repo or the intermediate google code repo.

You can then start announcing your fork on distro mailing list and see if they are willing to include it once you feel it's good enough.

**Comment by Jamim** [comment]
> That would be kind of irresponsible if the repo owners do that, repos get hijacked with malware getting added that way.

Hi @asl97,

English isn't my first language, but what you just wrote looks to me like you're trying to say that if current maintainers decide to grant write permissions to whoever they want, then it will **necessarily** lead to malware injection. For me, this statement is too bold.

There is always some risk, but it doesn't mean you shouldn't even try.

When the options are
* _some_ risk of hijacking, but with a _major_ chance of success
* or _inevitable_ death of the project due to lack of free time

I believe it makes sense to choose a risky approach first instead of burying `lincity-ng` with no attempt to give it a new life.

**Comment by asl97** [comment]
>     * or _inevitable_ death of the project due to lack of free time
> 
> 
> I believe it makes sense to choose a risky approach first instead of burying `lincity-ng` with no attempt to give it a new life.

The original maintainers at sourceforge didn't gave access and this fork managed just fine,  there no reason why someone else couldn't just fork it and then get attention themselves like what this repo maintainers did and others like it.

The maintainers here has ties to fedora, this is not just yet another fork by just another random person, there are responsibility to make sure whoever gain access is trustworthy and if the current maintainers don't have the time to make sure patches are safe to merge, they shouldn't rush to merge change.

**Comment by v1993** [comment]
A 5c from me: I've asked to be added as a maintainer a while ago via #54. Seeing how this project was stagnating, I hoped I'd be able to dedicate time and effort if not to actively contributing to it, then at least to reviewing PRs. Unfortunately, that never came to pass to the extent I hoped it would -- I never got to really work on it for a variety of real-life reasons.

I'd suggest those interested in working on this project to go ahead and ask for write access - the worst that could happen is that such request will be denied. As for worry about malware injection, consider that if distros will start packaging a fork, then from security perspective it will be no different from gaining write access to the original repo.

**Comment by asl97** [comment]
> if distros will start packaging a fork, then from security perspective it will be no different from gaining write access to the original repo.

That's not really the case, a forked project would only affect other packages that depend on the fork, if a malware filled version of a package was uploaded under a seperate name, nothing would really happen unless the users downloaded the malicious package, while write access to the original package will affect all packages that depend on the original, just see npm.

If the distro/repo replaced the original package with the fork, that's a whole other issue.

Although in this case, this is a game that's near the top of the software stack so the risk factor is greatly reduced, but there would still be users who updates all packages with their package manager.

Any decent distro/repo would at least take a quick look through the diff before pushing live and keep watch on updates for a while and also checking the diff on updates after a long time of inactivity instead of just having an implied trust, especially from a fork with no track record.

~~npm is clearly not one of those since they allowed malware pass via random updates to obscure downstream packages.~~

From the issue you linked, around Sep 2021, you had some ties with yuzu and other big open source project so there is some implied trustworthyness to you, no offense @dbear496,

Personally I wouldn't trust giving access to accounts with similar records like myself. (big rage rant some years ago over some dumb thing)

____

On other note, fun fact, this repo itself didn't get into fedora repo until Sep 2016, https://src.fedoraproject.org/rpms/lincity-ng/c/9daf1ee7511d4a8ca5931a9840ced58122802b83.patch , almost 2 years after the first commit by a github account on this repo https://github.com/lincity-ng/lincity-ng/commit/4900c2e5519afe86546c665de37b6a9541b76a20 , and it stayed on the 2016 version until 2021 https://bodhi.fedoraproject.org/updates/FEDORA-2021-019f9cf50f.

debian and ubuntu seem to both be at 2015 version, https://packages.qa.debian.org/l/lincity-ng.html

Arch still uses the sourceforge version.
https://gitlab.archlinux.org/archlinux/packaging/packages/lincity-ng/-/blob/main/PKGBUILD?ref_type=heads

@dbear496 Since you already did quite a bit and if you plan on doing bigger changes, you might be better off as a fork with a new name and separate config folder, no concerns about backward compatibility, on both yourside and the distro side.

old config can mess with a program, I saw it once and submitted a patch with a bug report.

**Comment by asl97** [comment]
> Since Berlios and later Google closed down Github is the original website. Is there something else I don't know or forgot about? Wolfgang

Berlios was close until 2019? someone brought it back and almost everywhere* is linking to it and it links to sourceforge

The project homepage was at http://lincity-ng.berlios.de/ 
2014: https://web.archive.org/web/20140403110244/http://lincity-ng.berlios.de/
2019: https://web.archive.org/web/20190416092537/http://lincity-ng.berlios.de/

That link now redirects to https://www.berlios.de/software/lincity-ng/

Now that I took a closer look, it was probably hijacked for SEO linking with other questionable stuff on the domain.

* such as [libregamewiki](https://libregamewiki.org/LinCity-NG), distros repo meta data ([fedora](https://packages.fedoraproject.org/pkgs/lincity-ng/lincity-ng-data/), [debian](https://wiki.debian.org/Games/lincity-ng)), [fsf](https://directory.fsf.org/wiki/LinCityNG), [the google code wiki](https://code.google.com/archive/p/lincity-ng/wikis/todo_developpers.wiki) and much more

> Sourceforge? Is that for Lincity or for NG?

"ng", it's still there, not sure if the svn source code history still exists though, but there is still the tar.bz, which is as far as I am aware of, still used by some distro for their builds

https://sourceforge.net/projects/lincity-ng.berlios/files/

> IIRC Alain tried to set up something at Fedorahosted. Did not work out too well because he is unreachable since a long time. Wolfgang

The mailing list still exists 
https://lists.fedorahosted.org/admin/lists/lincity-ng-devel.lists.fedorahosted.org/

Using the download button a editing the parameters in the url, there still seem to be some traffic, latest being 2021.

**Comment by uafr** [comment]
On 2023-11-27 asl97 ***@***.***> wrote:
> Berlios was close until 2019? someone brought it back and almost
> everywhere* is linking to it and it links to sourceforge

At first glance this looks like someone from a tropical island
grabbed the domain and put outdated stuff back on. I guess they
still get lots of links from article that never got updated.

Wolfgang

**Comment by dbear496** [comment]
@uafr thanks for the invite.

I appreciate the concern that people have about adding me to the project. I strongly agree that it is best for more eyes to be on new code coming into any project -- both for security and for testing. So I sincerely hope that from time to time someone will review recent and pending changes.

I also would like to make it clear that I do not intend to add commits willy-nilly. I will submit all changes through PR's and leave them open for comment for a sufficient time. (I am thinking at least one week for critical fixes and at least two weeks for features and non-critical fixes.) And I am more than happy to extend this period (within reason) to accommodate someone who will review the changes.

**Comment by Jamim** [comment]
For the sake of transparency, here it is: https://github.com/lincity-ng/lincity-ng/releases/tag/lincity-ng-2.9.0
