### ISSUE TITLE
[Enhancement request] remove screen resolutions that not fit the Aspect ratio of the current screen 

### ISSUE THREAD

**Issue by Mannshoch** [lincity-ng/lincity-ng#95]
1. Remove screen resolutions that not fit the Aspect ratio of the current screen from the settings page.
1. If the app get moved to another screen with different Screen size choose the nearest screen resolution from the screen before from available aspect ratio of this new screen.

**Comment by dbear496** [comment]
It sounds to me like you are experiencing an issue with some sort of graphics distortion or cropping. Is this true? Could you provide a screenshot of the issue?

It would also be useful for me to know some information about your system.
- What operating system are you using?
- If you are using Linux, are you using X or Wayland display server?
- How did you install Lincity-NG? (i.e. from source, through a package manager, etc.)
- What version of Lincity-NG are you using? If you could find the approximate date on which your version was built, that would be even better.
- Are you using windowed or fullscreen mode within Lincity-NG?

To be clear, in ArchLinux with Wayland, I do not have any issues with graphics distortion or cropping both in fullscreen and in windowed mode. For me, the game graphics automatically resize to fit the screen resolution (in fullscreen mode) or the window size (in windowed mode). However, I am interested to understand the issue you are having so that I can improve the game experience on other systems.

**Comment by Mannshoch** [comment]
>     * What operating system are you using?
Ubuntu 23.10
>     * If you are using Linux, are you using X or Wayland display server?
Wayland 

>     * How did you install Lincity-NG? (i.e. from source, through a package manager, etc.)
>     * What version of Lincity-NG are you using? If you could find the approximate date on which your version was built, that would be even better.
lincity-ng/mantic,now 2.9~git20150314-5 amd64

>     * Are you using windowed or fullscreen mode within Lincity-NG?
Screen1 2560x1440 (with lincityng in fullscreen mode) 
Screen2 2560x1080 
See attached Animated GIF from screenrecording 
![Unbenanntes Projekt02](https://github.com/lincity-ng/lincity-ng/assets/7795891/c94f7993-8b05-475a-87af-e658e49df296)

**Comment by dbear496** [comment]
From the gif you sent, it appears that you load Lincity-NG in 2560x1440 (which matches your screen resolution) and then you manually change the resolution to 2048x1536, which does not match your screen resolution. The result is Lincity-NG does not fill the full width of your screen.

If the aspect ratio/resolution is correct to begin with, why do you need to set it manually? The purpose of this setting is to accommodate systems where the aspect ratio/resolution does not auto-detect properly. Thus on those systems, using faulty auto-detection to reduce the options for this setting would defeat the purpose of having the setting in the first place.

If you move Lincity-NG from one screen to another, it should auto-detect the size of the new screen and adapt to that resolution.

Are you wanting to play Lincity-NG in fullscreen with a resolution lower than that of your screen..._why?_ If the issue is that some game elements are too small to see, read, or interact with, then there are better solutions I could implement.

**Comment by Mannshoch** [comment]
I do not know where this problem came from. The size in the gif is correct because I changed it while testing the screen recording. Interesting is also that If I go to settings change from Full-screen to wndowed, switch the window to the second screen and then set it to Full-screen it changes the resolution to the second screen but the full-screen appear with this setting on the Main screen. So I get borders.

**Comment by dbear496** [comment]
It sounds like the game is not resetting the resolution when switching monitors while in fullscreen mode.

**Comment by dbear496** [comment]
Pardon me if I still don't fully understand your issue, but it sounds to me like the game resolution is incorrect on fullscreen startup. The issue does not have to do with moving the game from one monitor to another.

I have confirmed this issue at [src/lincity-ng/main.cpp:591](https://github.com/lincity-ng/lincity-ng/blob/d4066f9e37d0f48d121fcb35c3f9e07ca9de188d/src/lincity-ng/main.cpp#L591). In fullscreen mode, the video size should be initialized to the detected screen size, not the stored configuration.

**Comment by dbear496** [comment]
So even though the screen size may not be auto-detected on startup in fullscreen, if you set the screen size (either manually or by toggling window mode on and then off), then the new screen size should be written to your config. Next time you start up LinCity-NG, it should remember this previous screen size and set the screen size to that. Are you seeing some different behavior?

**Comment by dbear496** [comment]
According to [this line](https://github.com/lincity-ng/lincity-ng/blob/9f49069661b7dc4918136fc78c5e3a538fea2f62/src/lincity-ng/MainMenu.cpp#L616), you shouldn't be able to change the resolution at all while in fullscreen mode! This is very strange.

**Comment by dbear496** [comment]
The resolution selector is only to select the size of the window in windowed mode. In fullscreen mode, it reads "fullscreen" and doesn't allow changing the resolution. Are you sure your are actually in fullscreen mode? (It's difficult to tell from the GIF.) If you are in fullscreen mode, how did you get into fullscreen mode? I expect this is a fullscreen feature offered by your window manager and not the fullscreen mode offered in Lincity-NG.

**Comment by Mannshoch** [comment]
I don't think that a resolution is the correct tool in Windowed mode. personally I would prefer a way like the zooming in Webbrowsers like with `CTRL + `

**Comment by dbear496** [comment]
Window size and zoom are completely separate issues. Zooming the game view can be done with the scroll wheel or the on-screen zoom buttons. If you would like to have zooming in other places (e.g. the help windows), then perhaps open a separate issue.

**Comment by Mannshoch** [comment]
Perhaps a strange question, but why do you have to deal with resolutions at all? They are actually dependent on the monitor anyway. I haven't changed anything for ages and I wonder why there are any left for the end user to customize. I used to change the resolution because my grandmother had bad eyesight and that was back when there was no zoom function.

**Comment by dbear496** [comment]
The answer is: I don't think the resolution needs to be set by the user -- the option was just there to begin with, and I haven't taken it out of the menu.

Also, "resolution" is a really bad name for it because it isn't really resolution, but rather it is the window size when in windowed mode. It has no bearing on how large or small things are drawn on the screen. You can see this if you go to the options menu, switch to windowed mode, and then resize your window by dragging the corner of the screen around: You can see the "resolution" option actively change as you resize the window.
