### ISSUE TITLE
[Build suggestion] Please add a pre-compiled release for non-devs

### ISSUE THREAD

**Issue by Miguelinileugim** [lincity-ng/lincity-ng#96]
I have only very rudimentary programming skills, figuring out how to get vcpkg and cmake to work is a huge mess that would probably take me an hour to figure out (I've already spent 20 minutes and am still confused). It's also a deterrent for people who want to play the updated release without delving with beginner level programming. Please add a pre-compiled windows release, thanks.

**Comment by Miguelinileugim** [comment]
(by compiled I meant built, I don't even know if there's a difference, I feel like a caveman trying to build IKEA furniture, help)

**Comment by dbear496** [comment]
Thanks for reaching out. I would like to provide release binaries; I just haven't gotten around to it yet.

On another note, I would be interested to hear what issues you are running into when building from source. Perhaps I can improve the instructions in the readme.

**Comment by Miguelinileugim** [comment]
> Thanks for reaching out. I would like to provide release binaries; I just haven't gotten around to it yet.
> 
> On another note, I would be interested to hear what issues you are running into when building from source. Perhaps I can improve the instructions in the readme.

- It didn't tell me I had to install cmake or vcpkg
- It's unclear if the <path to vcpkg> in -DCMAKE_TOOLCHAIN_FILE=<path to vcpkg>/scripts/buildsystems/vcpkg.cmake should be written like this:
  cmake -B build -DCMAKE_TOOLCHAIN_FILE=C:\Applications\vcpkg/scripts/buildsystems/vcpkg.cmake
or like this
  cmake -B build -DCMAKE_TOOLCHAIN_FILE="C:\Applications\vcpkg/scripts/buildsystems/vcpkg.cmake"
- It gives me a "does not appear to contain cmakelists.txt" error when I try to run it

I don't know how time consuming is it to add the binaries but I've done a tiny amount of programming myself and this feels like a mess. To someone wholly inexperienced this might as well be hieroglyphs.

**Comment by demotomohiro** [comment]
LinCity-NG is written in C++, so it requires C++ compiler like GCC.
And it uses CMake to build the project.
It might better to add C++ compiler (GCC, clang, etc) and CMake to prerequisites in README.md.

> It didn't tell me I had to install cmake or vcpkg

I think vcpkg is optional.
Required packages can be installed using package manager on Linux.
I used [MSYS2](https://www.msys2.org) on Windows to install them before.

> * It's unclear if the <path to vcpkg> in -DCMAKE_TOOLCHAIN_FILE=/scripts/buildsystems/vcpkg.cmake should be written like this:
>   cmake -B build -DCMAKE_TOOLCHAIN_FILE=C:\Applications\vcpkg/scripts/buildsystems/vcpkg.cmake
>   or like this
>   cmake -B build -DCMAKE_TOOLCHAIN_FILE="C:\Applications\vcpkg/scripts/buildsystems/vcpkg.cmake"

If that path doesn't contains any space, it probably doesn't need double quote.
But whether you needs to add double quote to an argument or not is depends on if the argument contains space or other special characters.
This is a problem related to the shell rather than CMake.

You will get confused if you use a tool without reading the manual.
This page explains how to use CMake:
https://cmake.org/cmake/help/latest/manual/cmake.1.html

> It gives me a "does not appear to contain cmakelists.txt" error when I try to build it

You probably need to change current directory to the top lincity-ng directory.

I wrote a script to build LinCity-NG on Windows before:
https://github.com/demotomohiro/lincity-ng-build-windows
And here is prebuild binary:
https://github.com/demotomohiro/lincity-ng-build-windows/releases
But it git clone and builds my old LinCity-NG fork, not latest up stream one.
As I no longer have MS Windows, I cannot update and test it.
This script might still works if this line
https://github.com/demotomohiro/lincity-ng-build-windows/blob/main/lincity_ng_build_cmake.nims#L31
is changed to 
```
msys2Shell.execQuote(["git", "clone", "--depth", "1", "--shallow-submodules", "--recurse-submodules", "https://github.com/lincity-ng/lincity-ng.git"], msys2RootDir)
```

Possible problem about releasing pre-compiled for MS Windows is, antivirus software might detect it as virus or malware even if the executable file doesn't contains any virus or malware code.
That happened to [Nim](https://forum.nim-lang.org/t/7885) and [GCC](https://github.com/msys2/MINGW-packages/issues/10295).
Most of people would understand that it is false positive.
But some people might think it is a real virus.

**Comment by Miguelinileugim** [comment]
Thanks! It still sounds a nightmare to setup but at least the instructions help. I think it's okay if some antivirus gives a false positive because any user dumb enough to think it is a real virus has no hope of being smart enough to go through the compiling process.

**Comment by yowshi** [comment]
ok so the instructions issue has gotten worse. the install instructions use cmake but none of the latest release options hjave cmakelists.txt they have jamfiles

**Comment by dbear496** [comment]
First off, you should reference the readme that comes with your version of the project -- not necessarily the latest readme from GitHub. The build tool was changed recently, thus changing how to build the project, so using the new build instructions on an old version of the project will not work.

Regarding your CMake version, you need at least version 3.21. I do not feel this is a high ask since that was released in 2021, over two and a half years ago. Perhaps you can check out the [CMake download page](https://cmake.org/download/) to download the latest version since the version in your distribution's repository is too far out of date.

**Comment by yowshi** [comment]
well that did solve my problems, but now it just keeps telling me ./Jamconfi no such file or directory. this just seems beyond me.

**Comment by dbear496** [comment]
@yowshi  Did you forget to run `./autogen.sh` and `./configure`?

**Comment by dbear496** [comment]
If you don't want to use cmake, then you can try cloning the `lincity-ng-2.9` branch.

**Comment by CirclesCenter** [comment]
I would also love to see compiled binaries for this game's releases if possible. 

I really think they'd help your project get the attention it deserves. I believe there area lot of people who would love to play but really don't want to set up and maintain a development environment they won't actually use. (Heck most people would be afraid of ruining their PC even with your instructions to follow)

I think with how poorly AAA citybuilders are doing right now the time is ripe for your project to get the same level of attention as games like OpenRCT2.

**Comment by dbear496** [comment]
I agree with the sentiment here: people just want to download a binary and have it work.

I've been researching how to make a binary package, and it is not straight forward to create a binary that "just works". Binaries are very sensitive to the library versions that the packager and user have in their respective environments. So much as a differing library version can cause the binary to not work.

Packagers for well known Linux distributions take care to compile packages in "clean" environments where library versions are likely compatible with other people using the same distribution. Documentation for packaging your own binaries for a distribution is lacking. The Ubuntu project appears to be working on such documentation, but it's not much more than a front page at this point. And packaging documentation for the Debian project is incomplete and outdated.

The bottom line is binary packaging is hard to get right, and even when it is done perfectly, it may not work for everyone. Compiling from source is more likely to work for more people.

And part of me wonders why people fear compiling from source. It is so easy. It takes only 2 commands: `cmake -B build` and `cmake --install build`. (Besides installing dependencies which is the case for a binary package as well.) And in case compiling from source doesn't work, then I am very willing to help, as doing so would likely bring to my attention a bug or at least a potential improvement.

So I see a few options:
1. I could stick with source distribution and not distribute any binary packages myself. Perhaps a Linux distribution will take notice and package lincity-ng themselves.
2. I could naively create a binary package without a clean environment. But the binary may not work for everyone. People can compile from source as a fallback.
3. I could put in the effort to build a binary package in a clean environment. However, I do not know how to do this, and information is very sparse online.

Because of this thread, I am strongly considering option 2. But if the binary doesn't work for someone, then it would likely turn them off of the project even more than needing to compile from source in the first place.

Obviously, everyone wants to see option 3 happen. But I don't know how to do it, and I have so far been unsuccessful in learning how to do it.

And I haven't even touched on the subject of a binary package for Windows. This has potential to be even more difficult since I do not have a Windows system.

**Comment by yowshi** [comment]
> And part of me wonders why people fear compiling from source. It is so easy. It takes only 3 commands: `cmake -B build`, `cmake --build build` and `cmake --install build`. (Besides installing dependencies which is the case for a binary package as well.) And in case compiling from source doesn't work, then I am very willing to help, as doing so would likely bring to my attention a bug or at least a potential improvement.


because it isn't actually that simple if you're not using it all the time. cmake was tricky enough to use that every time i used it i had to hit google to figure out how, because i didn't use it very often. not the release builds aren't using cmake they are using Jam. an install method i know nothing about and which seems even harder to use.
i just went through that on this board, installing this project from source is beyond my skills and knowledge base.

**Comment by dbear496** [comment]
There are two issues here: 1) building from source is difficult for some people, and thus 2) people want a binary package to make things easier. I would like to be clear that I recognize both these issues. No matter how easy or hard it is to build from source, I still want to distribute a binary package.

For the first issue, I would like to hear why people have trouble building from source. Are the instructions in the readme confusing? Does the build fail when following the instructions? Why do you need to fire up Google; are the instructions too brief? Is there something missing from the instructions? As far as I know, if anyone runs those three commands I listed, then lincity-ng will install to their system; I want to know if this is not the case.

For the second issue, I will do some more research into how to setup a clean environment to build binary packages. If I'm able to get that working, then great. If not, then I can try building a binary package in the environment I have and a few people can test it on their systems before I release it on GitHub.

As for Jam, I don't plan to ever release a binary for version 2.9.x. I only plan to release binaries for versions using CMake. I believe binaries already exist in some Linux distribution repositories that are very close to version 2.9.0 (though technically 2.9-beta).

**Comment by yowshi** [comment]
i would say what instructions in the readme. if you mean the ones in the actual release files, ./configure. jam run jam install as root?
that's a joke. i run ./configure and i get no such file or directory error. I tried cloning the repository which apparently can still use cmake and failed there too. 
sorry i am being all frustrated and it's comming out here. basically yes the instructions are insufficient. they aren't confusing they just don't exist.

**Comment by dbear496** [comment]
> i would say what instructions in the readme. if you mean the ones in the actual release files, ./configure. jam run jam install as root? that's a joke. i run ./configure and i get no such file or directory error. I tried cloning the repository which apparently can still use cmake and failed there too. sorry i am being all frustrated and it's comming out here. basically yes the instructions are insufficient. they aren't confusing they just don't exist.

Hmm, I see what you mean. I looked back at the instructions at 0f8746a, and it is not good -- notably missing the first step!Before running `./configure`, you have to run `./autogen.sh`, but this isn't mentioned until afterward! Though I have no plans to fix that release version -- there was a lot wrong with it and that is the reason for all my improvements working toward a version 2.10 release.

I would be very interested to hear how the CMake build failed for you (error messages etc.), so that I can learn how to make the build work for more people. In the [package-with-ubuntu-container branch](https://github.com/dbear496/lincity-ng/tree/package-with-ubuntu-container), I tried to make the instructions more concise; do you find them easier to follow?

**Comment by yowshi** [comment]
attempting to run ./autogen.sh gets permission denied, using sudo ./autrogen.sh gets command not found
i am using the WSL version of ubuntu, and yes i did go through the hassle of getting gui stuff to work on it.

**Comment by dbear496** [comment]
The [most recent release](https://github.com/lincity-ng/lincity-ng/releases/tag/lincity-ng-2.10.0) includes binary packages for Linux.
